[project]
name = "mock-huawei"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "edclol", email = "jessepinkmansmail@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
mock-huawei = "mock_huawei.main:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
